language: R
cache: packages
R: bioc-release
dist: trusty

os:
  - linux

env:
  - R_BIOC_VERSION: "3.11"

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master