# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp function for matrix
#' @param A a matrix
#' @param B a matrix
#' @param C a matrix
#'
#' @return A matrix
#'
#' @export
eigenMapMatMult <- function(A, B, C) {
    .Call('_CiteFuse_eigenMapMatMult', PACKAGE = 'CiteFuse', A, B, C)
}

