# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wtmRcpp <- function(x, w) {
    .Call(`_CiteFuse_wtmRcpp`, x, w)
}

wtvRcpp <- function(x, w) {
    .Call(`_CiteFuse_wtvRcpp`, x, w)
}

corRcpp <- function(X) {
    .Call(`_CiteFuse_corRcpp`, X)
}

covRcpp <- function(X, norm_type = 0L) {
    .Call(`_CiteFuse_covRcpp`, X, norm_type)
}

vlrRcpp <- function(X) {
    .Call(`_CiteFuse_vlrRcpp`, X)
}

clrRcpp <- function(X) {
    .Call(`_CiteFuse_clrRcpp`, X)
}

alrRcpp <- function(X, ivar = 0L) {
    .Call(`_CiteFuse_alrRcpp`, X, ivar)
}

symRcpp <- function(X) {
    .Call(`_CiteFuse_symRcpp`, X)
}

phiRcpp <- function(X, sym = 1L) {
    .Call(`_CiteFuse_phiRcpp`, X, sym)
}

rhoRcpp <- function(X, lr, ivar = 0L) {
    .Call(`_CiteFuse_rhoRcpp`, X, lr, ivar)
}

indexPairs <- function(X, op = "==", ref = 0) {
    .Call(`_CiteFuse_indexPairs`, X, op, ref)
}

indexToCoord <- function(V, N) {
    .Call(`_CiteFuse_indexToCoord`, V, N)
}

coordToIndex <- function(row, col, N) {
    .Call(`_CiteFuse_coordToIndex`, row, col, N)
}

linRcpp <- function(rho, lr) {
    .Call(`_CiteFuse_linRcpp`, rho, lr)
}

lltRcpp <- function(X) {
    .Call(`_CiteFuse_lltRcpp`, X)
}

urtRcpp <- function(X) {
    .Call(`_CiteFuse_urtRcpp`, X)
}

labRcpp <- function(nfeats) {
    .Call(`_CiteFuse_labRcpp`, nfeats)
}

half2mat <- function(X) {
    .Call(`_CiteFuse_half2mat`, X)
}

ratiosRcpp <- function(X) {
    .Call(`_CiteFuse_ratiosRcpp`, X)
}

lr2vlr <- function(lr) {
    .Call(`_CiteFuse_lr2vlr`, lr)
}

lr2rho <- function(lr) {
    .Call(`_CiteFuse_lr2rho`, lr)
}

